### ISSUE TITLE
let people know the repo has moved

### ISSUE THREAD

**Issue by shimwell** [fusion-energy/inertial_fusion_openmc_dagmc_paramak_example#4]
@tjlaboss I noticed you had stared the repo which I've now moved over here. Sorry for the inconvenience. I have been rounding up a couple of repos into the same org recently. You might also be interested in this other one which is similar https://github.com/fusion-energy/magnetic_fusion_openmc_dagmc_paramak_example

**Comment by tjlaboss** [comment]
Thank you, Jonathan.
